# Site settings
title: A blog by Duke Seo
description: about IT
baseurl: "/dev-duke" # the subpath of your site, e.g. /blog
url: "https://Dev-Duke-Seo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Duke Seo(서인덕)
user_description: Developer
user_title: Dev-DukeDeveloper
email: dev.duke.seo@gmail.com
github_username: Dev-Duke-Seo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
